import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

import { PRESETS } from "../src/selection/vocabulary.ts";
import { RULES } from "../src/selection/rules.ts";

const scriptPath = fileURLToPath(new URL("../scripts/gen-views.ts", import.meta.url));
const skillPath = fileURLToPath(
  new URL("../.claude/skills/prancheta/SKILL.md", import.meta.url),
);
const agentsPath = fileURLToPath(new URL("../AGENTS.md", import.meta.url));

const GENERATED_WARNING =
  "<!-- GENERATED by scripts/gen-views.ts — do not edit by hand. The selection " +
  "narrative inside is hand-written and lives in docs/selection/SELECTION.md. -->";

// --- STALENESS ---------------------------------------------------------------

test("committed generated views match what the generator produces (--check exits 0)", () => {
  const result = spawnSync(process.execPath, [scriptPath, "--check"], { encoding: "utf8" });
  assert.equal(
    result.status,
    0,
    `gen-views.ts --check failed:\nstdout: ${result.stdout}\nstderr: ${result.stderr}`,
  );
});

// --- INTEGRITY -----------------------------------------------------------------

const skillText = readFileSync(skillPath, "utf8");
const agentsText = readFileSync(agentsPath, "utf8");

test("SKILL.md and AGENTS.md both carry the GENERATED warning", () => {
  assert.ok(skillText.includes(GENERATED_WARNING), "SKILL.md missing GENERATED warning");
  assert.ok(agentsText.includes(GENERATED_WARNING), "AGENTS.md missing GENERATED warning");
});

test("SKILL.md has YAML frontmatter with name: prancheta", () => {
  const frontmatterMatch = skillText.match(/^---\n([\s\S]*?)\n---/);
  assert.ok(frontmatterMatch, "SKILL.md has no YAML frontmatter block");
  assert.match(frontmatterMatch![1]!, /^name:\s*prancheta\s*$/m);
});

test("every preset id in PRESETS appears in both SKILL.md and AGENTS.md", () => {
  for (const preset of PRESETS) {
    assert.ok(skillText.includes(preset.id), `SKILL.md missing preset id "${preset.id}"`);
    assert.ok(agentsText.includes(preset.id), `AGENTS.md missing preset id "${preset.id}"`);
  }
});

test("every rule-id-shaped token referenced in SKILL.md exists in RULES", () => {
  // Rule ids look like S-xxx or I-xxx. Restrict to tokens that actually start
  // with "S-" or "I-" to avoid false positives from unrelated hyphenated words.
  const ruleIdPattern = /\b[SI]-[a-z0-9]+(?:-[a-z0-9]+)*\b/g;
  const found = new Set(skillText.match(ruleIdPattern) ?? []);
  const knownIds = new Set(RULES.map((rule) => rule.id));
  const unknownTokens = [...found].filter((token) => !knownIds.has(token));
  assert.deepEqual(
    unknownTokens,
    [],
    `tokens in SKILL.md matching the rule-id shape but absent from RULES: ${unknownTokens.join(", ")}`,
  );
});
