/**
 * Generate the host-specific views of the knowledge tree.
 *
 * Decision 0002 draws a line here and it matters: the NARRATIVE is hand-written
 * and never machine-authored, because comparative selection judgement cannot be
 * assembled from per-preset docs. What is generated is the STRUCTURE around it
 * — the repertoire index, the invocation notes, the frontmatter — plus a
 * verbatim copy of the narrative into each view.
 *
 * Copying is not authoring. Generating the index is what stops a preset being
 * renamed in code while three documents keep advertising the old name.
 *
 * Output is deterministic: no timestamps, no ordering that depends on the
 * filesystem. A test regenerates everything and fails if the result differs
 * from what is committed, so a stale view is a red build rather than a
 * discovery months later.
 *
 *   node scripts/gen-views.ts          write the views
 *   node scripts/gen-views.ts --check  exit 1 if any view is stale
 */

import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { COMMANDS } from "../src/commands.ts";
import { PRESETS, PRESET_AREA, PRESET_AREAS } from "../src/selection/vocabulary.ts";
import { CHECK_CATALOGUE, CHECK_FAMILIES } from "../src/checks-catalogue.ts";
import { knowledgeResources } from "../src/mcp/server.ts";
import { MODULES, exampleArgs } from "../src/modules/repertoire.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export type GeneratedView = { path: string; content: string };

/**
 * Embedding a document moves it, and its relative links do not move with it.
 * A preset doc links to `../../../fixtures/x.json` from `src/presets/<id>/`;
 * copied verbatim into `.claude/skills/prancheta/SKILL.md` that path points at
 * nothing. Rewrite each link so it still resolves from where the copy lands.
 */
function rewriteLinks(markdown: string, fromDir: string, toDir: string): string {
  return markdown.replace(/\]\(([^)\s]+)\)/g, (whole, target: string) => {
    if (/^[a-z]+:\/\//i.test(target) || target.startsWith("#")) return whole;
    const [path, anchor] = target.split("#");
    const absolute = resolve(fromDir, path!);
    const rewritten = relative(toDir, absolute).split(sep).join("/");
    return `](${rewritten}${anchor === undefined ? "" : `#${anchor}`})`;
  });
}

async function readNarrative(toDir: string): Promise<string> {
  const from = join(root, "docs", "selection");
  return rewriteLinks(await readFile(join(from, "SELECTION.md"), "utf8"), from, toDir);
}

async function readPresetDoc(id: string, toDir: string): Promise<string> {
  const from = join(root, "src", "presets", id);
  return rewriteLinks(await readFile(join(from, "PRESET.md"), "utf8"), from, toDir);
}

/** One line per preset, from the code — never retyped by hand. */
function repertoireTable(): string {
  const rows = PRESETS.map(
    (preset) =>
      `| \`${preset.id}\` | ${preset.summary} | ${preset.implemented ? "yes" : "not yet"} |`,
  );
  return ["| preset | what it is | implemented |", "| --- | --- | --- |", ...rows].join("\n");
}

/**
 * The module repertoire, with a runnable example per row.
 *
 * Modules were absent from these views entirely, which made them unusable in
 * practice: an agent cannot reach for a figure kind nobody told it about. The
 * example command is the important column — "there is a circuit module" and
 * "here is how to draw a circuit" are separated by exactly the invocation
 * syntax, delimiters included, that this row supplies.
 */
function moduleTable(): string {
  const rows = MODULES.map((module) => {
    const needs =
      module.dependencies.length === 0 ? "—" : module.dependencies.map((d) => `\`${d}\``).join(", ");
    return `| \`${module.id}\` | ${module.summary} | ${needs} | \`--args "${exampleArgs(module)}"\` |`;
  });
  return [
    "| module | what it draws | needs | example |",
    "| --- | --- | --- | --- |",
    ...rows,
  ].join("\n");
}

function commandTable(): string {
  const rows = COMMANDS.map((command) => {
    const params = command.params
      .map((param) => (param.required === true ? `<${param.name}>` : `[--${param.name}]`))
      .join(" ");
    return `| \`${command.name}\` | ${params || "—"} | ${command.summary.split(". ")[0]}. |`;
  });
  return ["| command | arguments | what it does |", "| --- | --- | --- |", ...rows].join("\n");
}

function resourceTable(): string {
  const rows = knowledgeResources().map(
    (resource) => `| \`${resource.uri}\` | ${resource.name} |`,
  );
  return ["| uri | contents |", "| --- | --- |", ...rows].join("\n");
}

const GENERATED_WARNING =
  "<!-- GENERATED by scripts/gen-views.ts — do not edit by hand. The selection " +
  "narrative inside is hand-written and lives in docs/selection/SELECTION.md. -->";

/**
 * Function graphs and exercise sheets, said once for both views. Hand-written:
 * the tables above say what exists, this says how the two are meant to be
 * used together, which no table can.
 */
const SHEETS_SECTION = `## Function graphs and exercise sheets

A curve y = f(x) is the \`function-graph\` preset, and a figure is **data**:
functions are expressions (\`"x^2 - 4x + 1"\`, \`"1000(1 + 0.2t)"\`), points
are read off them (\`{"of": "f", "x": 3}\`), tangents and secants are computed
(\`{"tangent": {"of": "f", "at": 3}}\`, \`{"through": ["A", "B"]}\`), and every
label is a template filled from those values -- \`"P{coords}"\` prints
\`P(3; 9)\`. A coordinate pair typed into a label is refused. Numbers are
written by one pt-BR formatter (decimal comma, \`(2,5; 7,25)\`, the minus
\`−\`, \`17/3\` rather than \`5,667\`; from five integer digits a narrow
no-break space groups them, \`12 000\`, and a nonzero value is never written
as \`0\` -- \`0,000215\`). Axis numbers are never dropped,
the zero line is always drawn when the range contains zero, and the legend
finds its own free space. Four checks hold it to that: \`axis-number-present\`,
\`series-distinguishable-without-colour\` (label every curve on the drawing or
give it its own dash pattern -- a legend does not count),
\`curve-label-nearest-its-curve\` and \`feature-on-its-curve\` (a root lies on
its curve and on the x axis). Worked examples: \`fixtures/function-graph/\`.

Its sign table is the \`sign-chart\` preset: give it the same expression and
rows (\`"f"\`, \`"f'"\`, \`"f''"\`, \`"variation"\`, \`"concavity"\`, or
\`factors\` for an inequality) and it finds the roots, poles, signs and the
values at maxima and minima itself -- \`√3\`, not \`1,732\`. In a sheet, put
both in one exercise: \`"solutionFigure": [graph, table]\`, placed with
\`{{figure}}\` and \`{{figure2}}\`. Examples: \`fixtures/sign-chart/\`.

A whole exercise list is **one file** and the \`sheet\` command:

\`\`\`bash
node src/cli.ts sheet experiments/exercises/calculo1/lista.json
\`\`\`

Per exercise: \`level\` (easy/mid/hard), \`statement\` (HTML with KaTeX
\`\\\\( \\\\)\` and \`$$ $$\`), \`figure\` (\`{"graph": <function-graph input>,
"caption": ...}\`), \`answer\`, \`solution\`, \`solutionFigure\`. \`{{figure}}\`
marks where a figure goes; \`{{fig.P}}\` prints point P of the exercise's
figure through the same formatter as its label (TeX inside math, text
outside). The answer key is generated from \`answer\`, and the same field
closes each worked solution -- never type an answer twice.

A figure is also \`{"spec": <any preset input>}\` or \`{"module": {"args":
["modules/reaction/render.py", "--reaction=N.O>>[NH4+].[OH-]",
"--display=NH3;H2O>>NH4+;OH-", "--equilibrium"]}}\` -- a figure module run
and verified as the \`module\` command runs it (molecules with
\`--lone-pairs\`, reaction schemes). Chemistry text uses KaTeX's mhchem:
\`\\(\\ce{H2SO4 -> H+ + HSO4-}\\)\`. A chemistry example:
\`experiments/exercises/acidos-bases/lista.json\`.

Numbers the text and the figure share come from the exercise's \`params\`
(ADR 0040): \`{"a": 2, "b": "a + 1", "f(x)": "a*x^2", "A":
"integral(f(x), x, 0, b)"}\` -- numbers, expressions over other params, and
functions; a sheet-level \`params\` is shared by every exercise. In text,
\`{{= <expression>}}\` prints a computed value, exact when it is one (\`8/3\`,
\`√2\`, \`π/2\`), \`{{a}}\` prints a param and \`{{f}}\` a function's formula;
the expression may call \`integral(e, x, lo, hi)\`, \`deriv(e, x, at)\`,
\`lim(e, x, at[, left|right])\` (\`at\` may be \`inf\`) and \`f(2)\`, and a
pole, a corner or a limit that does not settle is refused. In a figure, a
string that is exactly \`"{{= b}}"\` becomes a number, and \`"{{f}}"\` or
\`"{{= a}}*x^2"\` fills an expression. Example:
\`experiments/exercises/parametros/lista.json\`. Output goes to
\`ProjectHub/Listas/<name>/\` (\`--out\` or \`PRANCHETA_SHEETS_DIR\` to change
it): figures, HTML, an A4 PDF, a PNG per page (PyMuPDF), and the source. The
command fails, naming each one, on a KaTeX error, a broken image or a figure
that failed a check. Look at the page PNGs before handing a sheet over: green
checks do not mean legible.

A figure's reading panel -- the computed lines a preset prints under its
drawing (a circuit's U_AB and powers, a lens's Gauss arithmetic) --
is lifted out of the drawing and set as page text under the image, with real
subscripts, at the page's size (ADR 0062); scaled with the figure it would
come out near 7pt. \`"readings": "drawing"\` on a figure, or on the sheet,
keeps it inside the drawing.

Fresh numbers for revision (ADR 0041, 0042): give an exercise
\`"variants": {"domains": {"b": {"int": [1, 4]}, "a": {"choice": ["1/2", 1,
2]}}, "predicates": [{"range": ["A", 0.1, 5]}]}\` -- which of its number
\`params\` are sampled (\`int\` with \`exclude\`, \`choice\`, \`decimal\`,
\`sign\`) and which draws are kept (\`integer\`, \`fraction\` with
\`maxDen\`, \`range\`, \`nonzero\`, \`positive\`, \`distinct\`, over any
param, derived ones included). Then \`sheet <file> --variants 3 [--seed S]\`
writes \`<name>-v1.html/.pdf\` ... \`<name>-v3\` (exercises only; version 1
is the author's own numbers), ONE \`<name>-gabarito.html/.pdf\` with every
version's answer key and worked solutions, and \`<name>-variants.json\`
(seed, each version's values, per exercise what was rejected and why).
A draw is admitted only if its params compute, its text resolves and every
figure renders with every check passing -- write figure ranges and units
as \`{{= …}}\` of the params, or most draws will be refused. The seed
defaults to the sheet's name and is printed on every page. An exercise that
cannot reach N distinct versions fails the build (\`--allowShortfall\`
repeats instead). \`--answers separate\` splits a single build the same way.`;

async function skillView(): Promise<GeneratedView> {
  const outPath = join(root, ".claude", "skills", "prancheta", "SKILL.md");
  const outDir = dirname(outPath);
  const narrative = await readNarrative(outDir);
  const presetSections: string[] = [];
  for (const preset of PRESETS) {
    const doc = await readPresetDoc(preset.id, outDir);
    // Drop the doc's own H1; it becomes a section here. The \r? is load-bearing
    // on Windows: `.` does not match \r, so against a CRLF working tree this
    // matched nothing and every preset section shipped a duplicate heading.
    const body = doc.replace(/^# .*\r?\n/, "").trim();
    presetSections.push(`### ${preset.id}\n\n${body}`);
  }

  const content = `---
name: prancheta
description: >-
  Draw complex figures — schematics, graphs, mind maps, annotated figures — as
  verified vector output. Use when a request asks for a diagram, figure,
  schematic, mind map or annotated illustration, especially when a flowchart
  would be the wrong answer.
---

${GENERATED_WARNING}

# Prancheta

Figures as code, with the geometry checked and repaired before you see them.

## How to run it

\`\`\`bash
node src/cli.ts <command> [options]
\`\`\`

${commandTable()}

Start with \`select\`. Then write a preset input as JSON and \`render\` it. Every
render prints its checks; a figure that fails them is reported, never hidden.

## The repertoire

${repertoireTable()}

## Figure modules

When none of the presets fits because the *geometry* is the problem — a pie
wedge is not a rectangle, a map needs a projection, a molecule needs stereo
perception — check whether a module already draws it before authoring raw IR.
These run as separate Python processes and are verified the same way: the module
declares what it drew, the core measures it.

${moduleTable()}

\`--args\` is repeatable and each occurrence is taken verbatim, which is why
several modules use \`;\` and \`:\` as delimiters rather than commas. Read
\`modules/README.md\` for the protocol and the limits.

${SHEETS_SECTION}

---

${narrative.replace(/^# .*\n/, "# Choosing what to draw\n")}

---

## The presets in detail

${presetSections.join("\n\n")}
`;

  return { path: outPath, content };
}

async function agentsView(): Promise<GeneratedView> {
  const content = `${GENERATED_WARNING}

# Prancheta — notes for agents

Prancheta turns a figure specification into checked SVG. It measures text in the
same browser engine that draws it, repairs geometric defects, and reports what it
could not fix.

## Before drawing, choose

The failure this project exists to prevent is reaching for a flowchart because a
flowchart is available. Run \`select\` with what the content *is* and how it must
be *drawn*; it answers with a preset, a composition of two, or "no preset fits —
author raw IR".

Read \`docs/selection/SELECTION.md\` for the reasoning. It is hand-written and it
is the part worth reading.

## Running the tests

**If you are changing this code, reach for the first command, not the last.**
Every render drives a real browser, so a full run costs about a minute — and
almost none of that minute concerns the file you just edited.

| command | when | cost |
| --- | --- | --- |
| \`npm run test:one <file>\` | you changed one thing | ~2s |
| \`npm run test:fast\` | a broad sweep while iterating | ~51s |
| \`npm test\` | before committing — the core suite | ~61s |
| \`npm run test:modules\` | you touched \`modules/\`; needs Python | slow |
| \`npm run test:all\` | both, and what \`check:all\` runs | slowest |

\`test:one\` forwards anything \`node --test\` accepts, so
\`npm run test:one -- --test-name-pattern="sRGB" tests/colour.test.ts\` runs a
single test.

**The suite is split by dependency, not by strictness.** Sixteen test files
spawn \`python\` and fail loudly when an interpreter or a module import is
missing — a probe that goes quietly green is indistinguishable from one that
never ran. That is right for a maintainer and wrong as a first impression, so
\`npm test\` is the core suite (Node and Chromium only) and the Python set is
asked for by name. Membership is derived in \`scripts/run-tests.ts\` by reading
each test's own source, never from a hand-kept list that would drift silently.
Install the module dependencies with
\`python -m pip install -r modules/requirements.txt\`.

\`test:fast\` turns off PNG rasterisation, which is most of a render. It
therefore does **not** prove the figure a reader receives can be produced, and
it never substitutes for \`npm test\` at a commit. Only \`tests/render.test.ts\`
reads the pixels, and it asks for them explicitly so the flag cannot hollow it
out.

**Do not interrupt a run.** \`node --test\` workers outlive their parent on
Windows, and each abandoned cohort silently slows every measurement that
follows — enough to move a 69s baseline past 600s. If a run is killed, reap
them before trusting another timing:

\`\`\`powershell
Get-CimInstance Win32_Process -Filter "Name='node.exe'" |
  Where-Object { $_.CommandLine -match 'trace-event-file-pattern' } |
  ForEach-Object { Stop-Process -Id $_.ProcessId -Force }
\`\`\`

## Adding a preset or a feature

Follow the procedure in \`CONTRIBUTING.md\` ("The procedure for a new preset
or feature", ADR 0075). The code change and the document change land together:

- **Checked by the build:** \`tests/preset-completeness.test.ts\` requires
  each preset's doc, fixtures in \`fixtures/<id>/\`, a test, its ADR, a shelf
  in \`PRESET_AREA\` and a selection rule. \`npm run check:docs\` fails on a
  stale README table, view or ADR index.
- **Not checked:** the plan row in \`docs/plans/\`, the TODO pruning and the
  ROADMAP entry are on you.
- **Before you finish:** run \`npm run gen:views\`, and look at every new PNG.

## Commands

${commandTable()}

## Repertoire

${repertoireTable()}

## Figure modules

Figure kinds the core cannot draw with its own box-model IR — a pie wedge is not
a rectangle, a map needs a projection, a molecule needs stereo perception. These
run as separate Python processes: the module declares what it drew, the core
measures it, and a module never certifies its own work.

Run one with \`module python --args "<script>,<flags>"\`. \`--args\` is repeatable
and each occurrence is taken verbatim, which is why several modules use \`;\` and
\`:\` as delimiters rather than commas.

${moduleTable()}

Read \`modules/README.md\` for the protocol, what the core checks, and the
standing limit: these verify malformation, never misrepresentation.

${SHEETS_SECTION}

## Over MCP

\`node src/mcp/server.ts\` speaks MCP over stdio. The same commands appear as
tools, generated from the same table, and the knowledge tree is served as
resources:

${resourceTable()}
`;

  return { path: join(root, "AGENTS.md"), content };
}

// ---- README regions and the decision index (ADR 0075) ----------------------
//
// The README is hand-written prose with tables in it, and the tables were what
// went stale: "seven presets" with thirty-three shipped, "nineteen checks" with
// thirty-five. Each table now sits between markers and is filled from code;
// the prose around it stays hand-written.

function readmePresetTable(): string {
  const out: string[] = [];
  for (const [area, title] of Object.entries(PRESET_AREAS)) {
    const rows = PRESETS.filter((p) => p.implemented && PRESET_AREA[p.id] === area);
    if (rows.length === 0) continue;
    out.push(`**${title}**`, "", "| preset | what it is |", "| --- | --- |");
    for (const p of rows) out.push(`| [\`${p.id}\`](src/presets/${p.id}/PRESET.md) | ${p.summary} |`);
    out.push("");
  }
  return out.join("\n").trimEnd();
}

function readmeCheckTable(): string {
  const out: string[] = [];
  for (const [family, title] of Object.entries(CHECK_FAMILIES)) {
    const rows = Object.entries(CHECK_CATALOGUE).filter(([, c]) => c.family === family);
    out.push(`**${title}** (${rows.length})`, "", "| check | what it asks |", "| --- | --- |");
    for (const [id, c] of rows) out.push(`| \`${id}\` | ${c.asks} |`);
    out.push("");
  }
  return out.join("\n").trimEnd();
}

function readmeCommandTable(): string {
  const rows = COMMANDS.map((command) => {
    const required = command.params.filter((p) => p.required === true).map((p) => ` <${p.name}>`).join("");
    const flags = command.params.filter((p) => p.required !== true).map((p) => `\`--${p.name}\``).join(" ");
    return `| \`${command.name}${required}\` | ${command.summary.split(". ")[0]}. ${flags} |`;
  });
  return ["| command | what it does |", "| --- | --- |", ...rows].join("\n");
}

function readmeCounts(): string {
  const presets = PRESETS.filter((p) => p.implemented).length;
  const core = Object.values(CHECK_CATALOGUE).filter((c) => c.family !== "module" && c.family !== "motion").length;
  return `**${presets} presets, ${core} checks on every figure, ${MODULES.length} figure modules.**`;
}

/** Fill every `<!-- generated:name -->…<!-- /generated:name -->` region; a missing marker is an error, never a silent skip. */
function fillRegions(text: string, regions: Record<string, string>): string {
  let out = text;
  for (const [name, body] of Object.entries(regions)) {
    const re = new RegExp(`(<!-- generated:${name} -->)[\\s\\S]*?(<!-- /generated:${name} -->)`);
    if (!re.test(out)) throw new Error(`README.md has no <!-- generated:${name} --> region`);
    out = out.replace(re, (_whole, open: string, close: string) => `${open}\n${body}\n${close}`);
  }
  return out;
}

async function readmeView(): Promise<GeneratedView> {
  const path = join(root, "README.md");
  const text = (await readFile(path, "utf8")).replace(/\r\n/g, "\n");
  const content = fillRegions(text, {
    counts: readmeCounts(),
    presets: readmePresetTable(),
    checks: readmeCheckTable(),
    commands: readmeCommandTable(),
    modules: moduleTable(),
  });
  return { path, content };
}

/** The ADR index: number, title and status, read from each record's own head. */
async function decisionsIndexView(): Promise<GeneratedView> {
  const dir = join(root, "docs", "decisions");
  const names = (await readdir(dir)).filter((n) => /^\d{4}-.*\.md$/.test(n)).sort();
  const rows: string[] = [];
  for (const name of names) {
    const lines = (await readFile(join(dir, name), "utf8")).replace(/\r\n/g, "\n").split("\n");
    const heading = lines.find((l) => l.startsWith("# ")) ?? name;
    const title = heading
      .replace(/^# /, "")
      .replace(/^(Decision|ADR)\s+\d{4}\s*[:—-]\s*/i, "")
      .replace(/^\d{4}\s*[:—-]\s*/, "")
      .trim();
    const at = lines.findIndex((l) => /^(\*\*)?status/i.test(l.replace(/^## /, "")));
    let status = "";
    if (at >= 0) {
      const inline = lines[at]!.replace(/^\*\*Status:\*\*\s*/i, "").replace(/^## Status\s*/i, "").trim();
      status = inline || (lines.slice(at + 1).find((l) => l.trim() !== "") ?? "").trim();
    }
    // Other records the status block names (amended by, corrects, removed by):
    // the chain a reader would otherwise find only by opening each one.
    const block = at < 0 ? "" : lines.slice(at, at + 8).join(" ").split(/ ## /)[0]!;
    const related = [...new Set([...block.matchAll(/\b(\d{4})\b/g)].map((m) => m[1]!))]
      .filter((n) => n !== name.slice(0, 4) && names.some((x) => x.startsWith(`${n}-`)));
    status = status.replace(/\s*·.*$/, "").replace(/[.;(].*$/, "").replace(/\*\*/g, "").trim();
    const see = related.length === 0 ? "" : `; see ${related.map((n) => `[${n}](${names.find((x) => x.startsWith(`${n}-`))})`).join(", ")}`;
    rows.push(`| [${name.slice(0, 4)}](${name}) | ${title.replace(/\|/g, "\\|")} | ${status}${see} |`);
  }
  const content = [
    "<!-- GENERATED by scripts/gen-views.ts from each record's heading and status — do not edit by hand. -->",
    "",
    "# Decisions",
    "",
    "Architecture decision records, oldest first. Each one says what was decided, why, and what it",
    "cost. A new one takes the next free number; how to write one is in [CONTRIBUTING.md](../../CONTRIBUTING.md#writing-an-adr).",
    "",
    `Next free number: **${String(Number(names.at(-1)!.slice(0, 4)) + 1).padStart(4, "0")}**.`,
    "",
    "| # | decision | status |",
    "| --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
  return { path: join(dir, "README.md"), content };
}

export async function generateViews(): Promise<GeneratedView[]> {
  return [await skillView(), await agentsView(), await readmeView(), await decisionsIndexView()];
}

const checkOnly = process.argv.includes("--check");
const views = await generateViews();
let stale = 0;

for (const view of views) {
  const existing = await readFile(view.path, "utf8").catch(() => null);
  if (existing === view.content) {
    if (!checkOnly) console.log(`unchanged  ${view.path}`);
    continue;
  }
  stale += 1;
  if (checkOnly) {
    console.error(`STALE  ${view.path}`);
    continue;
  }
  await mkdir(dirname(view.path), { recursive: true });
  await writeFile(view.path, view.content, "utf8");
  console.log(`${existing === null ? "created" : "updated"}    ${view.path}`);
}

if (checkOnly && stale > 0) {
  console.error(`\n${stale} generated view(s) are stale. Run: node scripts/gen-views.ts`);
  process.exitCode = 1;
}
