/**
 * Palette-reference generator.
 *
 * Renders `docs/design/PALETTE.generated.md` from `src/theme.ts` and
 * `src/colour/` so the reference can never claim a contrast ratio or a
 * distinguishability distance the code does not actually produce. Every
 * number below is computed by calling `contrastRatio()` and
 * `simulatedDistance()` on the live theme data -- the same functions
 * `contrast-sufficient` and `categorical-colours-distinguishable` call at
 * render time. A hand-typed table of these numbers would be wrong the moment
 * anyone touched a hex value in theme.ts, and nothing would notice.
 *
 * Mechanical on purpose. Why a variant exists and when to reach for one
 * belongs in the hand-written narrative; decision 0007 is that narrative
 * until this repertoire is large enough to earn its own page the way effects
 * did.
 *
 *   node scripts/gen-palette-reference.ts
 *   node scripts/gen-palette-reference.ts --check   exit 1 if the file is stale
 */

import { readFile, writeFile } from "node:fs/promises";
import { THEMES } from "../src/theme.ts";
import type { Role, ThemeDefinition } from "../src/theme.ts";
import { WCAG_AA_NORMAL, contrastRatio } from "../src/colour/contrast.ts";
import { DICHROMACY_KINDS, MIN_DISTINGUISHABLE_DISTANCE, simulatedDistance } from "../src/colour/colourblind.ts";

const OUTPUT = "docs/design/PALETTE.generated.md";
const SOURCE = "src/theme.ts";

function round(value: number): number {
  return Math.round(value * 100) / 100;
}

function roleRow(name: Role, theme: ThemeDefinition): string {
  const role = theme.roles[name];
  const ratio = contrastRatio(role.text, role.fill === "transparent" ? theme.canvas.background : role.fill);
  const cell = ratio === null ? "n/a" : `${round(ratio)}:1`;
  const verdict = ratio === null ? "?" : ratio >= WCAG_AA_NORMAL ? "PASS" : "FAIL";
  return `| \`${name}\` | \`${role.fill}\` | \`${role.stroke}\` | \`${role.text}\` | ${cell} | ${verdict} |`;
}

const lines: string[] = [];

lines.push("<!-- GENERATED FILE. Do not hand-edit. -->");
lines.push(`<!-- Generated by scripts/gen-palette-reference.ts from ${SOURCE} and src/colour/. -->`);
lines.push("");
lines.push("# Palette reference");
lines.push("");
lines.push(
  `This file is generated from \`${SOURCE}\` and \`src/colour/contrast.ts\`. Regenerate it ` +
    "with `node scripts/gen-palette-reference.ts` after any change to a theme's colours; do " +
    "not edit it by hand. Every contrast ratio below is computed by the same function " +
    "`contrast-sufficient` calls at render time, against the exact fill each role resolves to.",
);
lines.push("");
lines.push(
  "The reasoning -- why colour is checked rather than merely chosen, and what the two new " +
    "checks do and do not verify -- is " +
    "[decision 0007](../decisions/0007-colour-is-checked-not-chosen.md).",
);
lines.push("");

for (const theme of Object.values(THEMES)) {
  lines.push(`## \`${theme.name}\``);
  lines.push("");
  lines.push(`Canvas background \`${theme.canvas.background}\`.`);
  lines.push("");
  lines.push("| role | fill | stroke | text | text/fill contrast | WCAG AA (4.5:1) |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const name of Object.keys(theme.roles) as Role[]) {
    lines.push(roleRow(name, theme));
  }
  lines.push("");
}

lines.push("## Categorical distinguishability");
lines.push("");
lines.push(
  "The chart preset's series palette (`palette.blue`, `.red`, `.green`, `.yellow`, " +
    "`.magenta`, from `src/theme.ts`), checked pairwise under both dichromacy simulations. " +
    `The floor is ${MIN_DISTINGUISHABLE_DISTANCE} (see \`colour/colourblind.ts\`); a distance ` +
    "below it is what `categorical-colours-distinguishable` fails on.",
);
lines.push("");
lines.push("| pair | deuteranopia | protanopia |");
lines.push("| --- | --- | --- |");

const { palette } = await import("../src/theme.ts");
const seriesNames = Object.keys(palette) as (keyof typeof palette)[];
for (let i = 0; i < seriesNames.length; i += 1) {
  for (let j = i + 1; j < seriesNames.length; j += 1) {
    const a = seriesNames[i]!;
    const b = seriesNames[j]!;
    const cells = DICHROMACY_KINDS.map((kind) => {
      const distance = simulatedDistance(palette[a], palette[b], kind)!;
      const verdict = distance >= MIN_DISTINGUISHABLE_DISTANCE ? "OK" : "TOO CLOSE";
      return `${round(distance)} ${verdict}`;
    });
    lines.push(`| \`${a}\` vs \`${b}\` | ${cells[0]} | ${cells[1]} |`);
  }
}
lines.push("");

const content = `${lines.join("\n")}\n`;
const summary = `${Object.keys(THEMES).length} themes, ${seriesNames.length} palette colours`;

if (process.argv.includes("--check")) {
  const existing = await readFile(OUTPUT, "utf8").catch(() => null);
  if (existing === content) {
    console.log(`up to date  ${OUTPUT} (${summary})`);
  } else {
    console.error(
      `STALE  ${OUTPUT}\n` +
        "  A theme or the palette changed and this reference was not regenerated.\n" +
        "  Run: node scripts/gen-palette-reference.ts",
    );
    process.exit(1);
  }
} else {
  await writeFile(OUTPUT, content);
  console.log(`Wrote ${OUTPUT} (${summary}).`);
}
