/**
 * Rule-reference generator.
 *
 * Renders `docs/selection/RULES.generated.md` from `src/selection/rules.ts`
 * so the reference doc can never drift silently out of sync with the table
 * it describes. This file is mechanical on purpose: it states what each rule
 * does, not why — the "why" belongs in the hand-written narrative at
 * `docs/selection/SELECTION.md`, which a citation-coverage test checks
 * against this same rule table.
 *
 *   node scripts/gen-rule-reference.ts
 *   node scripts/gen-rule-reference.ts --check   exit 1 if the file is stale
 */

import { readFile, writeFile } from "node:fs/promises";
import { FLOOR, RULES } from "../src/selection/rules.ts";

const OUTPUT = "docs/selection/RULES.generated.md";
const SOURCE = "src/selection/rules.ts";

const lines: string[] = [];

lines.push("<!-- GENERATED FILE. Do not hand-edit. -->");
lines.push(`<!-- Generated by scripts/gen-rule-reference.ts from ${SOURCE}. -->`);
lines.push("");
lines.push("# Rule reference");
lines.push("");
lines.push(
  `This file is generated from \`${SOURCE}\`. Regenerate it with ` +
    "`node scripts/gen-rule-reference.ts` after any change to the rule table; do not edit it by hand.",
);
lines.push("");
lines.push(`**FLOOR:** a candidate must reach a score of \`${FLOOR}\` to be offered at all.`);
lines.push("");

for (const rule of RULES) {
  lines.push(`## ${rule.id}`);
  lines.push("");
  lines.push(`- **Axis:** ${rule.axis}`);
  lines.push(`- **When:** \`${rule.when}\``);
  lines.push(`- **Preset:** \`${rule.preset}\``);
  lines.push(
    rule.effect === "favour"
      ? `- **Effect:** favours (weight \`${rule.weight}\`)`
      : "- **Effect:** disqualifies",
  );
  lines.push(`- **Priority:** ${rule.priority}`);
  lines.push(`- **Statement:** ${rule.statement}`);
  lines.push("");
}

const content = lines.join("\n");

if (process.argv.includes("--check")) {
  const existing = await readFile(OUTPUT, "utf8").catch(() => null);
  if (existing === content) {
    console.log(`up to date  ${OUTPUT} (${RULES.length} rules)`);
  } else {
    console.error(
      `STALE  ${OUTPUT}\n` +
        "  The rule table changed and this reference was not regenerated.\n" +
        "  Run: node scripts/gen-rule-reference.ts",
    );
    process.exit(1);
  }
} else {
  await writeFile(OUTPUT, content);
  console.log(`Wrote ${OUTPUT} (${RULES.length} rules).`);
}
