/**
 * Generate the host-specific views of the knowledge tree.
 *
 * Decision 0002 draws a line here and it matters: the NARRATIVE is hand-written
 * and never machine-authored, because comparative selection judgement cannot be
 * assembled from per-preset docs. What is generated is the STRUCTURE around it
 * — the repertoire index, the invocation notes, the frontmatter — plus a
 * verbatim copy of the narrative into each view.
 *
 * Copying is not authoring. Generating the index is what stops a preset being
 * renamed in code while three documents keep advertising the old name.
 *
 * Output is deterministic: no timestamps, no ordering that depends on the
 * filesystem. A test regenerates everything and fails if the result differs
 * from what is committed, so a stale view is a red build rather than a
 * discovery months later.
 *
 *   node scripts/gen-views.ts          write the views
 *   node scripts/gen-views.ts --check  exit 1 if any view is stale
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { COMMANDS } from "../src/commands.ts";
import { PRESETS } from "../src/selection/vocabulary.ts";
import { knowledgeResources } from "../src/mcp/server.ts";
import { MODULES, exampleArgs } from "../src/modules/repertoire.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export type GeneratedView = { path: string; content: string };

/**
 * Embedding a document moves it, and its relative links do not move with it.
 * A preset doc links to `../../../fixtures/x.json` from `src/presets/<id>/`;
 * copied verbatim into `.claude/skills/prancheta/SKILL.md` that path points at
 * nothing. Rewrite each link so it still resolves from where the copy lands.
 */
function rewriteLinks(markdown: string, fromDir: string, toDir: string): string {
  return markdown.replace(/\]\(([^)\s]+)\)/g, (whole, target: string) => {
    if (/^[a-z]+:\/\//i.test(target) || target.startsWith("#")) return whole;
    const [path, anchor] = target.split("#");
    const absolute = resolve(fromDir, path!);
    const rewritten = relative(toDir, absolute).split(sep).join("/");
    return `](${rewritten}${anchor === undefined ? "" : `#${anchor}`})`;
  });
}

async function readNarrative(toDir: string): Promise<string> {
  const from = join(root, "docs", "selection");
  return rewriteLinks(await readFile(join(from, "SELECTION.md"), "utf8"), from, toDir);
}

async function readPresetDoc(id: string, toDir: string): Promise<string> {
  const from = join(root, "src", "presets", id);
  return rewriteLinks(await readFile(join(from, "PRESET.md"), "utf8"), from, toDir);
}

/** One line per preset, from the code — never retyped by hand. */
function repertoireTable(): string {
  const rows = PRESETS.map(
    (preset) =>
      `| \`${preset.id}\` | ${preset.summary} | ${preset.implemented ? "yes" : "not yet"} |`,
  );
  return ["| preset | what it is | implemented |", "| --- | --- | --- |", ...rows].join("\n");
}

/**
 * The module repertoire, with a runnable example per row.
 *
 * Modules were absent from these views entirely, which made them unusable in
 * practice: an agent cannot reach for a figure kind nobody told it about. The
 * example command is the important column — "there is a circuit module" and
 * "here is how to draw a circuit" are separated by exactly the invocation
 * syntax, delimiters included, that this row supplies.
 */
function moduleTable(): string {
  const rows = MODULES.map((module) => {
    const needs =
      module.dependencies.length === 0 ? "—" : module.dependencies.map((d) => `\`${d}\``).join(", ");
    return `| \`${module.id}\` | ${module.summary} | ${needs} | \`--args "${exampleArgs(module)}"\` |`;
  });
  return [
    "| module | what it draws | needs | example |",
    "| --- | --- | --- | --- |",
    ...rows,
  ].join("\n");
}

function commandTable(): string {
  const rows = COMMANDS.map((command) => {
    const params = command.params
      .map((param) => (param.required === true ? `<${param.name}>` : `[--${param.name}]`))
      .join(" ");
    return `| \`${command.name}\` | ${params || "—"} | ${command.summary.split(". ")[0]}. |`;
  });
  return ["| command | arguments | what it does |", "| --- | --- | --- |", ...rows].join("\n");
}

function resourceTable(): string {
  const rows = knowledgeResources().map(
    (resource) => `| \`${resource.uri}\` | ${resource.name} |`,
  );
  return ["| uri | contents |", "| --- | --- |", ...rows].join("\n");
}

const GENERATED_WARNING =
  "<!-- GENERATED by scripts/gen-views.ts — do not edit by hand. The selection " +
  "narrative inside is hand-written and lives in docs/selection/SELECTION.md. -->";

async function skillView(): Promise<GeneratedView> {
  const outPath = join(root, ".claude", "skills", "prancheta", "SKILL.md");
  const outDir = dirname(outPath);
  const narrative = await readNarrative(outDir);
  const presetSections: string[] = [];
  for (const preset of PRESETS) {
    const doc = await readPresetDoc(preset.id, outDir);
    // Drop the doc's own H1; it becomes a section here.
    const body = doc.replace(/^# .*\n/, "").trim();
    presetSections.push(`### ${preset.id}\n\n${body}`);
  }

  const content = `---
name: prancheta
description: >-
  Draw complex figures — schematics, graphs, mind maps, annotated figures — as
  verified vector output. Use when a request asks for a diagram, figure,
  schematic, mind map or annotated illustration, especially when a flowchart
  would be the wrong answer.
---

${GENERATED_WARNING}

# Prancheta

Figures as code, with the geometry checked and repaired before you see them.

## How to run it

\`\`\`bash
node src/cli.ts <command> [options]
\`\`\`

${commandTable()}

Start with \`select\`. Then write a preset input as JSON and \`render\` it. Every
render prints its checks; a figure that fails them is reported, never hidden.

## The repertoire

${repertoireTable()}

## Figure modules

When none of the presets fits because the *geometry* is the problem — a pie
wedge is not a rectangle, a map needs a projection, a molecule needs stereo
perception — check whether a module already draws it before authoring raw IR.
These run as separate Python processes and are verified the same way: the module
declares what it drew, the core measures it.

${moduleTable()}

\`--args\` is repeatable and each occurrence is taken verbatim, which is why
several modules use \`;\` and \`:\` as delimiters rather than commas. Read
\`modules/README.md\` for the protocol and the limits.

---

${narrative.replace(/^# .*\n/, "# Choosing what to draw\n")}

---

## The presets in detail

${presetSections.join("\n\n")}
`;

  return { path: outPath, content };
}

async function agentsView(): Promise<GeneratedView> {
  const content = `${GENERATED_WARNING}

# Prancheta — notes for agents

Prancheta turns a figure specification into checked SVG. It measures text in the
same browser engine that draws it, repairs geometric defects, and reports what it
could not fix.

## Before drawing, choose

The failure this project exists to prevent is reaching for a flowchart because a
flowchart is available. Run \`select\` with what the content *is* and how it must
be *drawn*; it answers with a preset, a composition of two, or "no preset fits —
author raw IR".

Read \`docs/selection/SELECTION.md\` for the reasoning. It is hand-written and it
is the part worth reading.

## Commands

${commandTable()}

## Repertoire

${repertoireTable()}

## Figure modules

Figure kinds the core cannot draw with its own box-model IR — a pie wedge is not
a rectangle, a map needs a projection, a molecule needs stereo perception. These
run as separate Python processes: the module declares what it drew, the core
measures it, and a module never certifies its own work.

Run one with \`module python --args "<script>,<flags>"\`. \`--args\` is repeatable
and each occurrence is taken verbatim, which is why several modules use \`;\` and
\`:\` as delimiters rather than commas.

${moduleTable()}

Read \`modules/README.md\` for the protocol, what the core checks, and the
standing limit: these verify malformation, never misrepresentation.

## Over MCP

\`node src/mcp/server.ts\` speaks MCP over stdio. The same commands appear as
tools, generated from the same table, and the knowledge tree is served as
resources:

${resourceTable()}
`;

  return { path: join(root, "AGENTS.md"), content };
}

export async function generateViews(): Promise<GeneratedView[]> {
  return [await skillView(), await agentsView()];
}

const checkOnly = process.argv.includes("--check");
const views = await generateViews();
let stale = 0;

for (const view of views) {
  const existing = await readFile(view.path, "utf8").catch(() => null);
  if (existing === view.content) {
    if (!checkOnly) console.log(`unchanged  ${view.path}`);
    continue;
  }
  stale += 1;
  if (checkOnly) {
    console.error(`STALE  ${view.path}`);
    continue;
  }
  await mkdir(dirname(view.path), { recursive: true });
  await writeFile(view.path, view.content, "utf8");
  console.log(`${existing === null ? "created" : "updated"}    ${view.path}`);
}

if (checkOnly && stale > 0) {
  console.error(`\n${stale} generated view(s) are stale. Run: node scripts/gen-views.ts`);
  process.exitCode = 1;
}
