/**
 * Effect-reference generator.
 *
 * Renders `docs/effects/REFERENCE.generated.md` from `src/effects/` so the
 * reference can never drift out of sync with the code it describes. Every
 * number in the output is *computed*, not transcribed: defaults come from
 * resolving each effect with no options set, and every bleed figure comes from
 * `bleedOf()` — the same function checks.ts uses to decide whether a halo fits
 * on the canvas. A hand-written table of these numbers would be wrong within a
 * release and nothing would notice.
 *
 * Mechanical on purpose. What each effect is *for*, and when reaching for one
 * is a mistake, belongs in the hand-written narrative at
 * `docs/effects/EFFECTS.md`.
 *
 *   node scripts/gen-effect-reference.ts
 *   node scripts/gen-effect-reference.ts --check   exit 1 if the file is stale
 */

import { readFile, writeFile } from "node:fs/promises";
import {
  EFFECT_NAMES,
  EFFECT_PRESETS,
  appliesToLabel,
  resolveEffects,
} from "../src/effects/types.ts";
import type { Effect, EffectKind, ResolvedEffect } from "../src/effects/types.ts";
import { bleedOf, needsFilter } from "../src/effects/bleed.ts";
import type { Bleed } from "../src/effects/bleed.ts";

const OUTPUT = "docs/effects/REFERENCE.generated.md";
const SOURCE = "src/effects/types.ts";

/**
 * One instance of every effect kind, with nothing set beyond what is required.
 * Resolving these is what produces the documented defaults, so the table below
 * cannot claim a default the code does not actually apply.
 *
 * `tint` appears with a colour because it has no default one — that is itself
 * a documented fact, recorded in REQUIRED below rather than hidden by the
 * placeholder.
 */
const BARE: Effect[] = [
  { kind: "shadow" },
  { kind: "glow" },
  { kind: "blur" },
  { kind: "occlusion" },
  { kind: "brightness" },
  { kind: "saturate" },
  { kind: "tint", color: "#000000" },
  { kind: "grain" },
  { kind: "bevel" },
  { kind: "sheen" },
];

/** Parameters with no default: naming them is the point, so they are listed. */
const REQUIRED: Partial<Record<EffectKind, string[]>> = {
  tint: ["color"],
};

function bleedCell(bleed: Bleed): string {
  const all = [bleed.left, bleed.top, bleed.right, bleed.bottom];
  if (all.every((value) => value === 0)) return "none — stays inside its own bounds";
  if (all.every((value) => value === all[0])) return `${round(all[0]!)} on every side`;
  return (
    `left ${round(bleed.left)}, top ${round(bleed.top)}, ` +
    `right ${round(bleed.right)}, bottom ${round(bleed.bottom)}`
  );
}

function round(value: number): number {
  return Math.round(value * 100) / 100;
}

function paramsOf(effect: ResolvedEffect, kind: EffectKind): string {
  const required = new Set(REQUIRED[kind] ?? []);
  const entries = Object.entries(effect as Record<string, unknown>)
    .filter(([key]) => key !== "kind")
    .map(([key, value]) =>
      required.has(key)
        ? `\`${key}\` (required)`
        : `\`${key}\` = \`${JSON.stringify(value)}\``,
    );
  return entries.length === 0 ? "—" : entries.join(", ");
}

const lines: string[] = [];

lines.push("<!-- GENERATED FILE. Do not hand-edit. -->");
lines.push(`<!-- Generated by scripts/gen-effect-reference.ts from ${SOURCE}. -->`);
lines.push("");
lines.push("# Effect reference");
lines.push("");
lines.push(
  `This file is generated from \`${SOURCE}\` and \`src/effects/bleed.ts\`. Regenerate it ` +
    "with `node scripts/gen-effect-reference.ts` after any change to the effect table; do " +
    "not edit it by hand. Every default and every bleed figure below is computed by the " +
    "same code the renderer and the checks use.",
);
lines.push("");
lines.push(
  "The narrative — when an effect carries information and when reaching for one is a " +
    "mistake — is at [EFFECTS.md](EFFECTS.md).",
);
lines.push("");
lines.push("## Reading the bleed column");
lines.push("");
lines.push(
  "**Bleed** is how far past an element's own bounding box the effect puts ink, in SVG " +
    "user units. It is what the `effect-within-canvas` check measures against the canvas, " +
    "and what the repair loop grows `canvas.padding` to accommodate. An effect that bleeds " +
    "nothing can never be clipped.",
);
lines.push("");
lines.push(
  "The figures below are for each effect **at its default parameters**. Bleed scales with " +
    "the parameters — a larger `blur` or `radius` reaches further — and composes through a " +
    "chain in order, so a `blur` placed after a `shadow` spreads the shadow's already-offset " +
    "edge as well.",
);
lines.push("");

// --- effect kinds ---------------------------------------------------------

lines.push("## Effect kinds");
lines.push("");
lines.push(
  "The ten primitives. Any of these may be written inline in a spec as an object with a " +
    "`kind`; the named effects in the next section are compositions of them.",
);
lines.push("");
lines.push("| kind | parameters and defaults | bleed at defaults | follows a block's label | drawn as |");
lines.push("| --- | --- | --- | --- | --- |");

for (const bare of BARE) {
  const [resolved] = resolveEffects([bare]);
  if (resolved === undefined) continue;
  const bleed = bleedOf([resolved]);
  const drawnAs = needsFilter([resolved]) ? "SVG filter" : "painted geometry";
  lines.push(
    `| \`${bare.kind}\` | ${paramsOf(resolved, bare.kind)} | ${bleedCell(bleed)} | ` +
      `${appliesToLabel(bare.kind) ? "yes" : "no — surface only"} | ${drawnAs} |`,
  );
}
lines.push("");
lines.push(
  "**follows a block's label** distinguishes an effect describing the block as an object " +
    "(a shadow belongs to the surface; a label with its own shadow is embossed lettering) " +
    "from one describing its whole appearance (a blur that left the label sharp would read " +
    "as a bug). See EFFECTS.md for why a block is two SVG elements in the first place.",
);
lines.push("");

// --- named effects --------------------------------------------------------

lines.push("## Named effects");
lines.push("");
lines.push(
  `The ${EFFECT_NAMES.length} names a spec can use in a block's or connector's \`effect\` ` +
    "field, in place of a literal object. An unknown name is a `SpecError` at parse time, " +
    "never a silently skipped effect.",
);
lines.push("");
lines.push("| name | chain | bleed |");
lines.push("| --- | --- | --- |");

for (const name of EFFECT_NAMES) {
  const chain = resolveEffects(name);
  const kinds = chain.map((effect) => `\`${effect.kind}\``).join(" → ");
  lines.push(`| \`${name}\` | ${kinds} | ${bleedCell(bleedOf(chain))} |`);
}
lines.push("");

// --- full parameters per named effect -------------------------------------

lines.push("## Named effects in full");
lines.push("");
lines.push("Every parameter each named effect resolves to, including inherited defaults.");
lines.push("");

for (const name of EFFECT_NAMES) {
  const chain = resolveEffects(name);
  lines.push(`### \`${name}\``);
  lines.push("");
  for (const effect of chain) {
    lines.push(`- \`${effect.kind}\` — ${paramsOf(effect, effect.kind)}`);
  }
  lines.push("");
  lines.push(`Bleed: ${bleedCell(bleedOf(chain))}.`);
  lines.push("");
}

// --- canvas ---------------------------------------------------------------

lines.push("## Canvas vignette");
lines.push("");
lines.push(
  "`canvas.vignette` takes a number from 0 to 1 and darkens the figure's edges. It is not " +
    "in the table above because it is not a node effect: it is painted over the finished " +
    "figure as a radial wash, bounded by the canvas by construction, so it has no bleed and " +
    "can never be clipped. A value outside 0–1 is a `SpecError`.",
);
lines.push("");

const totalPresetEffects = EFFECT_NAMES.reduce(
  (sum, name) => sum + (EFFECT_PRESETS[name]?.length ?? 0),
  0,
);

const content = `${lines.join("\n")}\n`;
const summary =
  `${BARE.length} kinds, ${EFFECT_NAMES.length} named effects, ` +
  `${totalPresetEffects} composed steps`;

if (process.argv.includes("--check")) {
  const existing = await readFile(OUTPUT, "utf8").catch(() => null);
  if (existing === content) {
    console.log(`up to date  ${OUTPUT} (${summary})`);
  } else {
    console.error(
      `STALE  ${OUTPUT}\n` +
        "  The effect table changed and this reference was not regenerated.\n" +
        "  Run: node scripts/gen-effect-reference.ts",
    );
    process.exit(1);
  }
} else {
  await writeFile(OUTPUT, content);
  console.log(`Wrote ${OUTPUT} (${summary}).`);
}
